
package soap.unionexcel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UnionExcelService", targetNamespace = "http://localhost:12525/UnionExcel/UnionExcel.asmx", wsdlLocation = "http://frsi.convertpdf.local:12525/unionexcel/UnionExcel.asmx?wsdl")
public class UnionExcelService
    extends Service
{

    private final static URL UNIONEXCELSERVICE_WSDL_LOCATION;
    private final static WebServiceException UNIONEXCELSERVICE_EXCEPTION;
    private final static QName UNIONEXCELSERVICE_QNAME = new QName("http://localhost:12525/UnionExcel/UnionExcel.asmx", "UnionExcelService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://frsi.convertpdf.local:12525/unionexcel/UnionExcel.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNIONEXCELSERVICE_WSDL_LOCATION = url;
        UNIONEXCELSERVICE_EXCEPTION = e;
    }

    public UnionExcelService() {
        super(__getWsdlLocation(), UNIONEXCELSERVICE_QNAME);
    }

    public UnionExcelService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNIONEXCELSERVICE_QNAME, features);
    }

    public UnionExcelService(URL wsdlLocation) {
        super(wsdlLocation, UNIONEXCELSERVICE_QNAME);
    }

    public UnionExcelService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNIONEXCELSERVICE_QNAME, features);
    }

    public UnionExcelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnionExcelService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UnionExcelServiceSoap
     */
    @WebEndpoint(name = "UnionExcelServiceSoap")
    public UnionExcelServiceSoap getUnionExcelServiceSoap() {
        return super.getPort(new QName("http://localhost:12525/UnionExcel/UnionExcel.asmx", "UnionExcelServiceSoap"), UnionExcelServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UnionExcelServiceSoap
     */
    @WebEndpoint(name = "UnionExcelServiceSoap")
    public UnionExcelServiceSoap getUnionExcelServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:12525/UnionExcel/UnionExcel.asmx", "UnionExcelServiceSoap"), UnionExcelServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNIONEXCELSERVICE_EXCEPTION!= null) {
            throw UNIONEXCELSERVICE_EXCEPTION;
        }
        return UNIONEXCELSERVICE_WSDL_LOCATION;
    }

}
