
package soap.unionexcel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UnionExcelServiceSoap", targetNamespace = "http://localhost:12525/UnionExcel/UnionExcel.asmx")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UnionExcelServiceSoap {


    /**
     * 
     * @param dirPath
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://localhost:12525/UnionExcel/UnionExcel.asmx/union")
    @WebResult(name = "unionResult", targetNamespace = "http://localhost:12525/UnionExcel/UnionExcel.asmx")
    @RequestWrapper(localName = "union", targetNamespace = "http://localhost:12525/UnionExcel/UnionExcel.asmx", className = "soap.unionexcel.Union")
    @ResponseWrapper(localName = "unionResponse", targetNamespace = "http://localhost:12525/UnionExcel/UnionExcel.asmx", className = "soap.unionexcel.UnionResponse")
    public String union(
        @WebParam(name = "dirPath", targetNamespace = "http://localhost:12525/UnionExcel/UnionExcel.asmx")
        String dirPath);

}
