
package soap.excel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExcelServiceSoap", targetNamespace = "http://localhost:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExcelServiceSoap {


    /**
     * 
     * @param pdfFileName
     * @param fileName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://localhost:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx/convert")
    @WebResult(name = "convertResult", targetNamespace = "http://localhost:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx")
    @RequestWrapper(localName = "convert", targetNamespace = "http://localhost:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx", className = "soap.excel.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://localhost:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx", className = "soap.excel.ConvertResponse")
    public String convert(
        @WebParam(name = "fileName", targetNamespace = "http://localhost:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx")
        String fileName,
        @WebParam(name = "pdfFileName", targetNamespace = "http://localhost:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx")
        String pdfFileName);

}
