
package soap.excel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ExcelService", targetNamespace = "http://localhost:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx", wsdlLocation = "http://frsi.convertpdf.local:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx?WSDL")
public class ExcelService
        extends Service
{

    private final static URL EXCELSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXCELSERVICE_EXCEPTION;
    private final static QName EXCELSERVICE_QNAME = new QName("http://localhost:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx", "ExcelService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://frsi.convertpdf.local:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXCELSERVICE_WSDL_LOCATION = url;
        EXCELSERVICE_EXCEPTION = e;
    }

    public ExcelService() {
        super(__getWsdlLocation(), EXCELSERVICE_QNAME);
    }

    public ExcelService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXCELSERVICE_QNAME, features);
    }

    public ExcelService(URL wsdlLocation) {
        super(wsdlLocation, EXCELSERVICE_QNAME);
    }

    public ExcelService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXCELSERVICE_QNAME, features);
    }

    public ExcelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExcelService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ExcelServiceSoap
     */
    @WebEndpoint(name = "ExcelServiceSoap")
    public ExcelServiceSoap getExcelServiceSoap() {
        return super.getPort(new QName("http://localhost:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx", "ExcelServiceSoap"), ExcelServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExcelServiceSoap
     */
    @WebEndpoint(name = "ExcelServiceSoap")
    public ExcelServiceSoap getExcelServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:12525/ExcelToPdfConvert/ExcelToPdfConvert.asmx", "ExcelServiceSoap"), ExcelServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXCELSERVICE_EXCEPTION!= null) {
            throw EXCELSERVICE_EXCEPTION;
        }
        return EXCELSERVICE_WSDL_LOCATION;
    }

}
